from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from io import BytesIO
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from zoneinfo import ZoneInfo


@dataclass(frozen=True)
class StatementRow:
    timestamp: datetime | None
    transaction_id: str
    amount: float
    currency: str
    merchant: str | None
    merchant_category: str | None
    decision: str | None


def _fmt_dt(dt: datetime | None, tz: ZoneInfo, tz_label: str) -> str:
    if not dt:
        return "—"
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    local = dt.astimezone(tz)
    return local.strftime("%d %b %Y, %H:%M ") + tz_label


def render_statement_pdf(
    *,
    bank_name: str,
    customer_external_id: str,
    range_label: str,
    tz_name: str,
    rows: list[StatementRow],
    stats: dict[str, Any] | None = None,
) -> bytes:
    tz = ZoneInfo(tz_name)
    tz_label = "GMT" if tz_name == "Africa/Accra" else (datetime.now(tz).strftime("%Z") or tz_name)
    buf = BytesIO()

    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
        title="Transaction Statement",
        author=bank_name or "BankAI",
    )

    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph(f"<b>{bank_name or 'BankAI'}</b>", styles["Title"]))
    story.append(Paragraph("Account Transaction Statement", styles["Heading2"]))
    story.append(Spacer(1, 6))
    story.append(Paragraph(f"<b>Customer ID:</b> {customer_external_id}", styles["Normal"]))
    story.append(Paragraph(f"<b>Statement period:</b> {range_label}", styles["Normal"]))
    story.append(Paragraph(f"<b>Timezone:</b> {tz_label} ({tz_name})", styles["Normal"]))
    story.append(Spacer(1, 10))

    if stats:
        by = stats.get("by_decision") or {}
        parts = []
        for k in ("APPROVE", "LIMITED_APPROVAL", "REQUEST_OTP", "BLOCK"):
            if k in by:
                parts.append(f"{k}: {by.get(k)}")
        breakdown = ", ".join(parts) if parts else "—"
        story.append(Paragraph(f"<b>Total:</b> {stats.get('total_transactions', 0)}", styles["Normal"]))
        story.append(Paragraph(f"<b>Scored:</b> {stats.get('scored_transactions', 0)}", styles["Normal"]))
        story.append(Paragraph(f"<b>Fraud-like:</b> {stats.get('fraud_like_transactions', 0)} (BLOCK + REQUEST_OTP)", styles["Normal"]))
        story.append(Paragraph(f"<b>Decision breakdown:</b> {breakdown}", styles["Normal"]))
        story.append(Spacer(1, 10))

    data = [
        ["Date", "Transaction ID", "Amount", "Merchant/Type", "Decision"],
    ]
    for r in rows:
        merchant = r.merchant or r.merchant_category or "—"
        amt = f"{r.amount:,.2f} {r.currency}"
        data.append(
            [
                _fmt_dt(r.timestamp, tz, tz_label),
                r.transaction_id,
                amt,
                merchant,
                r.decision or "—",
            ]
        )

    table = Table(data, colWidths=[32 * mm, 40 * mm, 28 * mm, 52 * mm, 25 * mm])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 9),
                ("ALIGN", (2, 1), (2, -1), "RIGHT"),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#334155")),
                ("FONTSIZE", (0, 1), (-1, -1), 8),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ]
        )
    )
    story.append(table)
    story.append(Spacer(1, 10))
    story.append(Paragraph("Generated by BankAI Care.", styles["Normal"]))

    doc.build(story)
    return buf.getvalue()

